spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  resources:
    static-locations: file:src/main/resources/static/
    cache.period: 0

logging.level.org.springframework.web: DEBUG

#server:
#  port: 8443
#  ssl:
#    key-store: keystore.p12
#    key-store-password: password
#    keyStoreType: PKCS12
#    keyAlias: tomcat

mongodb:
  db: tweet-${spring.profiles.active}
  host: localhost
  port: 27017
  auth:
    username: user
    password: pass
    db: tweet-${spring.profiles.active}

com:
  dotterbear:
    twitter:
      consumer:
        key: ENC(YXga7pUcXl3vYtbwqz+pSaVayDc+mg2NOM4ZqZL0pYNZ7osEHSKobA==)
        secret: ENC(8covZl2NQkO2uFG5FrPEhQkT0UVGEscq6WY11W2RSstic5l/+PLvV9JYIEA1d7l+1wxmBvT8+Et0V0iMkbcacw==)
      access:
        token: ENC(acDrl5sLRV2srARF2szVOt8dvvvRHRxmKBYZr9dD/qQl3i6WEuF7suOoIDAlUBO05GYpguKCszzDhT3LLmyUww==)
        secret: ENC(Imv8SZROkJLNKJttXl7rlvhExD4V+YlLnbQa3yBEYAsbTknRbXpdXv453InsjztIlSZhOZKudBk=)
    format:
      request:
        tweet-date: "yyyy-MM-dd'T'HH:mmX"
    file:
      root-dir: upload-dir
      file-name-format: yyyy-MM-dd'T'hh:mm:ss.SSS'Z'